[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_mint = "vsiQm3wAcpWUKYJc9CgYCvmDvnZ78gmdMasiAL3pu1d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/amit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
